project:
  type: website
  output-dir: docs

website:
  title: "Portifólio DataScientist"
  navbar:
    left:
      - href: Principal.qmd
        text: Sobre
      - href: Estudos.qmd
        text: Trilhas de Conhecimento
      - href: Projetos.qmd
        text: Projetos
        
  favicon: iconfav.jpg
format:
  html:
    code-overflow: scroll
    lang: pt
    theme: flatly
    css: styles.css
    toc: true

editor: visual

