project:
  type: website
  output-dir: docs

website:
  title: "Portifólio DataScientist"
  navbar:
    left:
      - href: Principal.qmd
        text: Sobre
      - href: Estudos.qmd
        text: Trilhas de Conhecimento
      - href: Projetos.qmd
        text: Projetos

format:
  html:
    lang: pt
    theme: flatly
    css: styles.css
    toc: true

editor: visual

