project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Moreira  <br> <small> *DataScientist * </small>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: Sobre
      - href: Projetos.qmd
        text: Projetos
        
  favicon: iconfav.jpg
format:
  html:
    css: styles.css
    code-overflow: scroll
    lang: pt
    theme: 
      light: lux
    linkcolor: red
    toc: true
editor: visual


