project:
  type: website
  output-dir: docs
  
lightbox: true
code-block-bg: "#EEEEEE"
highlight-style: github
code-block-border-left: "#334061"
sidebar: false

python:
  path: "C:/Users/Gabriel/AppData/Local/Microsoft/WindowsApps/python.exe"

website:
  title: "Gabriel Moreira  <br> <small> *DataScientist * </small>"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: Sobre
      - href: Projetos.qmd
        text: Projetos
  favicon: iconfav.png
  sidebar:
    - id: loldash
      contents:
        - projetos/LolDashIC/index.qmd
        - section: Teoria
          contents:
            - href: projetos/LolDashIC/parte0/index.qmd
            
        - section: Prática
          contents:
            - href: projetos/LolDashIC/parte1/index.qmd
            - href: projetos/LolDashIC/parte2/index.qmd
format:
  html:
    css: styles.css
    code-overflow: scroll
    code-link: true
    lang: pt
    theme: 
      light: flatly
      dark: darkly
    toc: true
editor: visual


